// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthJwtLoginData,
  AuthJwtLoginErrors,
  AuthJwtLoginResponses,
  AuthJwtLogoutData,
  AuthJwtLogoutErrors,
  AuthJwtLogoutResponses,
  CreateAppData,
  CreateAppErrors,
  CreateAppResponses,
  CreateAssistantMessageData,
  CreateAssistantMessageErrors,
  CreateAssistantMessageResponses,
  CreateMessageData,
  CreateMessageErrors,
  CreateMessageResponses,
  CreateThreadData,
  CreateThreadErrors,
  CreateThreadResponses,
  DeleteAppData,
  DeleteAppErrors,
  DeleteAppResponses,
  DeleteThreadData,
  DeleteThreadErrors,
  DeleteThreadResponses,
  GetAppData,
  GetAppErrors,
  GetAppResponses,
  GetMessageData,
  GetMessageErrors,
  GetMessageResponses,
  GetSubscriberData,
  GetSubscriberErrors,
  GetSubscriberResponses,
  GetThreadData,
  GetThreadErrors,
  GetThreadResponses,
  ListMessagesData,
  ListMessagesErrors,
  ListMessagesResponses,
  ListSubscribersData,
  ListSubscribersErrors,
  ListSubscribersResponses,
  ListSubscriberThreadsData,
  ListSubscriberThreadsErrors,
  ListSubscriberThreadsResponses,
  ListThreadsData,
  ListThreadsErrors,
  ListThreadsResponses,
  ReadAppData,
  ReadAppErrors,
  ReadAppResponses,
  RegisterRegisterData,
  RegisterRegisterErrors,
  RegisterRegisterResponses,
  ResetForgotPasswordData,
  ResetForgotPasswordErrors,
  ResetForgotPasswordResponses,
  ResetResetPasswordData,
  ResetResetPasswordErrors,
  ResetResetPasswordResponses,
  RunStreamData,
  RunStreamErrors,
  RunStreamResponses,
  RunSyncData,
  RunSyncErrors,
  RunSyncResponses,
  UpdateAppData,
  UpdateAppErrors,
  UpdateAppResponses,
  UpdateThreadData,
  UpdateThreadErrors,
  UpdateThreadResponses,
  UsersCurrentUserData,
  UsersCurrentUserErrors,
  UsersCurrentUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserResponses,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserErrors,
  UsersPatchCurrentUserResponses,
  UsersPatchUserData,
  UsersPatchUserErrors,
  UsersPatchUserResponses,
  UsersUserData,
  UsersUserErrors,
  UsersUserResponses,
  VerifyRequestTokenData,
  VerifyRequestTokenErrors,
  VerifyRequestTokenResponses,
  VerifyVerifyData,
  VerifyVerifyErrors,
  VerifyVerifyResponses,
  WebhookTestData,
  WebhookTestErrors,
  WebhookTestResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read App
 */
export const readApp = <ThrowOnError extends boolean = false>(
  options?: Options<ReadAppData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadAppResponses,
    ReadAppErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/",
    ...options,
  });

/**
 * Create App
 */
export const createApp = <ThrowOnError extends boolean = false>(
  options: Options<CreateAppData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAppResponses,
    CreateAppErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete App
 */
export const deleteApp = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAppData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAppResponses,
    DeleteAppErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}",
    ...options,
  });

/**
 * Get App
 */
export const getApp = <ThrowOnError extends boolean = false>(
  options: Options<GetAppData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}",
    ...options,
  });

/**
 * Update App
 */
export const updateApp = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAppData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateAppResponses,
    UpdateAppErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Threads
 *
 * List threads for the specified app, ordered by updated_at desc.
 */
export const listThreads = <ThrowOnError extends boolean = false>(
  options: Options<ListThreadsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListThreadsResponses,
    ListThreadsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads",
    ...options,
  });

/**
 * Create Thread
 *
 * Create a new thread for the specified app.
 *
 * When no user message is provided (default), the backend adds an initial
 * assistant greeting as the clear entry point. The greeting is returned
 * in the response so the UI can show it instantly without a second request.
 */
export const createThread = <ThrowOnError extends boolean = false>(
  options: Options<CreateThreadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateThreadResponses,
    CreateThreadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Thread
 *
 * Delete a thread.
 */
export const deleteThread = <ThrowOnError extends boolean = false>(
  options: Options<DeleteThreadData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteThreadResponses,
    DeleteThreadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/threads/{thread_id}",
    ...options,
  });

/**
 * Get Thread
 *
 * Get a specific thread by ID.
 */
export const getThread = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetThreadResponses,
    GetThreadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/threads/{thread_id}",
    ...options,
  });

/**
 * Update Thread
 *
 * Update a thread.
 */
export const updateThread = <ThrowOnError extends boolean = false>(
  options: Options<UpdateThreadData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateThreadResponses,
    UpdateThreadErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/threads/{thread_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Messages
 *
 * List messages for a thread with cursor-based pagination.
 * Messages are ordered by seq ascending (oldest first).
 */
export const listMessages = <ThrowOnError extends boolean = false>(
  options: Options<ListMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListMessagesResponses,
    ListMessagesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads/{thread_id}/messages",
    ...options,
  });

/**
 * Create Message
 *
 * Append a new user message to the thread.
 *
 * This endpoint:
 * 1. Locks the thread row (SELECT FOR UPDATE)
 * 2. Reads and increments next_seq atomically
 * 3. Creates the message with role="user" and the allocated seq
 * 4. Updates thread.updated_at
 *
 * This approach guarantees concurrency-safe seq allocation.
 */
export const createMessage = <ThrowOnError extends boolean = false>(
  options: Options<CreateMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateMessageResponses,
    CreateMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads/{thread_id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Assistant Message
 *
 * Create an agent message (for partner/dashboard replies).
 *
 * This allows the business owner (partner) to manually reply as the agent
 * through the dashboard UI. The message is created with role="agent" and
 * content_json.source="dashboard_agent" for proper attribution.
 */
export const createAssistantMessage = <ThrowOnError extends boolean = false>(
  options: Options<CreateAssistantMessageData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAssistantMessageResponses,
    CreateAssistantMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads/{thread_id}/messages/assistant",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Message
 *
 * Get a specific message by ID.
 */
export const getMessage = <ThrowOnError extends boolean = false>(
  options: Options<GetMessageData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMessageResponses,
    GetMessageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/messages/{message_id}",
    ...options,
  });

/**
 * List Subscribers
 *
 * List subscribers for an app with pagination.
 *
 * Returns subscribers ordered by last_message_at DESC (most recent first),
 * with thread count and optional last message preview.
 */
export const listSubscribers = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscribersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListSubscribersResponses,
    ListSubscribersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/subscribers",
    ...options,
  });

/**
 * Get Subscriber
 *
 * Get subscriber detail.
 */
export const getSubscriber = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriberData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSubscriberResponses,
    GetSubscriberErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/subscribers/{subscriber_id}",
    ...options,
  });

/**
 * List Subscriber Threads
 *
 * List threads for a subscriber with pagination.
 *
 * Returns threads ordered by updated_at DESC (most recent first),
 * with message count and optional last message preview.
 */
export const listSubscriberThreads = <ThrowOnError extends boolean = false>(
  options: Options<ListSubscriberThreadsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ListSubscriberThreadsResponses,
    ListSubscriberThreadsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/subscribers/{subscriber_id}/threads",
    ...options,
  });

/**
 * Run Sync
 *
 * Run the orchestrator synchronously and return JSON result.
 */
export const runSync = <ThrowOnError extends boolean = false>(
  options: Options<RunSyncData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RunSyncResponses,
    RunSyncErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads/{thread_id}/run",
    ...options,
  });

/**
 * Run Stream
 *
 * Run the orchestrator and stream the response as SSE.
 *
 * If the partner returns SSE (text/event-stream), their stream is proxied
 * directly to the client. Otherwise, the orchestrator generates simulator
 * chunks locally.
 */
export const runStream = <ThrowOnError extends boolean = false>(
  options: Options<RunStreamData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RunStreamResponses,
    RunStreamErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/threads/{thread_id}/run/stream",
    ...options,
  });

/**
 * Webhook Test
 *
 * Test a webhook URL with a sample payload. Does NOT persist any messages.
 */
export const webhookTest = <ThrowOnError extends boolean = false>(
  options: Options<WebhookTestData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    WebhookTestResponses,
    WebhookTestErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}/webhook/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
