// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthJwtLoginData,
  AuthJwtLoginErrors,
  AuthJwtLoginResponses,
  AuthJwtLogoutData,
  AuthJwtLogoutErrors,
  AuthJwtLogoutResponses,
  CreateAppData,
  CreateAppErrors,
  CreateAppResponses,
  DeleteAppData,
  DeleteAppErrors,
  DeleteAppResponses,
  ReadAppData,
  ReadAppErrors,
  ReadAppResponses,
  RegisterRegisterData,
  RegisterRegisterErrors,
  RegisterRegisterResponses,
  ResetForgotPasswordData,
  ResetForgotPasswordErrors,
  ResetForgotPasswordResponses,
  ResetResetPasswordData,
  ResetResetPasswordErrors,
  ResetResetPasswordResponses,
  UsersCurrentUserData,
  UsersCurrentUserErrors,
  UsersCurrentUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserResponses,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserErrors,
  UsersPatchCurrentUserResponses,
  UsersPatchUserData,
  UsersPatchUserErrors,
  UsersPatchUserResponses,
  UsersUserData,
  UsersUserErrors,
  UsersUserResponses,
  VerifyRequestTokenData,
  VerifyRequestTokenErrors,
  VerifyRequestTokenResponses,
  VerifyVerifyData,
  VerifyVerifyErrors,
  VerifyVerifyResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read App
 */
export const readApp = <ThrowOnError extends boolean = false>(
  options?: Options<ReadAppData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadAppResponses,
    ReadAppErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/",
    ...options,
  });

/**
 * Create App
 */
export const createApp = <ThrowOnError extends boolean = false>(
  options: Options<CreateAppData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAppResponses,
    CreateAppErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete App
 */
export const deleteApp = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAppData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAppResponses,
    DeleteAppErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/apps/{app_id}",
    ...options,
  });
