// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * AppCreate
 */
export type AppCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * AppRead
 */
export type AppRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * MessageCreate
 *
 * Create message schema - role is always 'user' for public endpoint.
 */
export type MessageCreate = {
  /**
   * Content
   */
  content?: string | null;
  /**
   * Content Json
   */
  content_json?: {
    [key: string]: unknown;
  };
};

/**
 * MessageRead
 */
export type MessageRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Thread Id
   */
  thread_id: string;
  /**
   * Seq
   */
  seq: number;
  /**
   * Role
   */
  role: "user" | "assistant" | "system" | "tool";
  /**
   * Content
   */
  content?: string | null;
  /**
   * Content Json
   */
  content_json: {
    [key: string]: unknown;
  };
  /**
   * Created At
   */
  created_at: string;
};

/**
 * Page[AppRead]
 */
export type PageAppRead = {
  /**
   * Items
   */
  items: Array<AppRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * Page[ThreadRead]
 */
export type PageThreadRead = {
  /**
   * Items
   */
  items: Array<ThreadRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * ThreadCreate
 */
export type ThreadCreate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Customer Id
   */
  customer_id?: string | null;
};

/**
 * ThreadRead
 */
export type ThreadRead = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Customer Id
   */
  customer_id?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * App Id
   */
  app_id: string;
  /**
   * Status
   */
  status: "active" | "archived" | "deleted";
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ThreadUpdate
 */
export type ThreadUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Status
   */
  status?: "active" | "archived" | "deleted" | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ReadAppData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Size
     *
     * Page size
     */
    size?: number;
  };
  url: "/apps/";
};

export type ReadAppErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadAppError = ReadAppErrors[keyof ReadAppErrors];

export type ReadAppResponses = {
  /**
   * Successful Response
   */
  200: PageAppRead;
};

export type ReadAppResponse = ReadAppResponses[keyof ReadAppResponses];

export type CreateAppData = {
  body: AppCreate;
  path?: never;
  query?: never;
  url: "/apps/";
};

export type CreateAppErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAppError = CreateAppErrors[keyof CreateAppErrors];

export type CreateAppResponses = {
  /**
   * Successful Response
   */
  200: AppRead;
};

export type CreateAppResponse = CreateAppResponses[keyof CreateAppResponses];

export type DeleteAppData = {
  body?: never;
  path: {
    /**
     * App Id
     */
    app_id: string;
  };
  query?: never;
  url: "/apps/{app_id}";
};

export type DeleteAppErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAppError = DeleteAppErrors[keyof DeleteAppErrors];

export type DeleteAppResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListThreadsData = {
  body?: never;
  path: {
    /**
     * App Id
     */
    app_id: string;
  };
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Size
     *
     * Page size
     */
    size?: number;
    /**
     * Customer Id
     *
     * Filter by customer ID
     */
    customer_id?: string | null;
    /**
     * Status
     *
     * Filter by status
     */
    status?: string | null;
  };
  url: "/apps/{app_id}/threads";
};

export type ListThreadsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListThreadsError = ListThreadsErrors[keyof ListThreadsErrors];

export type ListThreadsResponses = {
  /**
   * Successful Response
   */
  200: PageThreadRead;
};

export type ListThreadsResponse =
  ListThreadsResponses[keyof ListThreadsResponses];

export type CreateThreadData = {
  body: ThreadCreate;
  path: {
    /**
     * App Id
     */
    app_id: string;
  };
  query?: never;
  url: "/apps/{app_id}/threads";
};

export type CreateThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateThreadError = CreateThreadErrors[keyof CreateThreadErrors];

export type CreateThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadRead;
};

export type CreateThreadResponse =
  CreateThreadResponses[keyof CreateThreadResponses];

export type DeleteThreadData = {
  body?: never;
  path: {
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: never;
  url: "/threads/{thread_id}";
};

export type DeleteThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteThreadError = DeleteThreadErrors[keyof DeleteThreadErrors];

export type DeleteThreadResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetThreadData = {
  body?: never;
  path: {
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: never;
  url: "/threads/{thread_id}";
};

export type GetThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetThreadError = GetThreadErrors[keyof GetThreadErrors];

export type GetThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadRead;
};

export type GetThreadResponse = GetThreadResponses[keyof GetThreadResponses];

export type UpdateThreadData = {
  body: ThreadUpdate;
  path: {
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: never;
  url: "/threads/{thread_id}";
};

export type UpdateThreadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateThreadError = UpdateThreadErrors[keyof UpdateThreadErrors];

export type UpdateThreadResponses = {
  /**
   * Successful Response
   */
  200: ThreadRead;
};

export type UpdateThreadResponse =
  UpdateThreadResponses[keyof UpdateThreadResponses];

export type ListMessagesData = {
  body?: never;
  path: {
    /**
     * App Id
     */
    app_id: string;
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: {
    /**
     * Before Seq
     *
     * Get messages before this sequence number (cursor pagination)
     */
    before_seq?: number | null;
    /**
     * Limit
     *
     * Maximum number of messages to return
     */
    limit?: number;
  };
  url: "/apps/{app_id}/threads/{thread_id}/messages";
};

export type ListMessagesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
  /**
   * Response Messages-List Messages
   *
   * Successful Response
   */
  200: Array<MessageRead>;
};

export type ListMessagesResponse =
  ListMessagesResponses[keyof ListMessagesResponses];

export type CreateMessageData = {
  body: MessageCreate;
  path: {
    /**
     * App Id
     */
    app_id: string;
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: never;
  url: "/apps/{app_id}/threads/{thread_id}/messages";
};

export type CreateMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
  /**
   * Successful Response
   */
  200: MessageRead;
};

export type CreateMessageResponse =
  CreateMessageResponses[keyof CreateMessageResponses];

export type CreateAssistantMessageData = {
  body: MessageCreate;
  path: {
    /**
     * App Id
     */
    app_id: string;
    /**
     * Thread Id
     */
    thread_id: string;
  };
  query?: never;
  url: "/apps/{app_id}/threads/{thread_id}/messages/assistant";
};

export type CreateAssistantMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAssistantMessageError =
  CreateAssistantMessageErrors[keyof CreateAssistantMessageErrors];

export type CreateAssistantMessageResponses = {
  /**
   * Successful Response
   */
  200: MessageRead;
};

export type CreateAssistantMessageResponse =
  CreateAssistantMessageResponses[keyof CreateAssistantMessageResponses];

export type GetMessageData = {
  body?: never;
  path: {
    /**
     * Message Id
     */
    message_id: string;
  };
  query?: never;
  url: "/messages/{message_id}";
};

export type GetMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMessageError = GetMessageErrors[keyof GetMessageErrors];

export type GetMessageResponses = {
  /**
   * Successful Response
   */
  200: MessageRead;
};

export type GetMessageResponse = GetMessageResponses[keyof GetMessageResponses];
