"""add_app_integration_fields

Revision ID: e4a06651998f
Revises: 0a762d207d9f
Create Date: 2026-02-15 01:21:55.489351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4a06651998f"
down_revision: Union[str, None] = "0a762d207d9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("webhook_url", sa.String(), nullable=True))
    op.add_column("apps", sa.Column("webhook_secret", sa.String(), nullable=True))
    op.add_column(
        "apps",
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "threads", sa.Column("customer_id", sa.String(length=128), nullable=True)
    )
    op.drop_index(op.f("ix_threads_app_external_user"), table_name="threads")
    op.create_index(
        "ix_threads_app_customer", "threads", ["app_id", "customer_id"], unique=False
    )
    op.drop_column("threads", "external_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads",
        sa.Column(
            "external_user_id",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index("ix_threads_app_customer", table_name="threads")
    op.create_index(
        op.f("ix_threads_app_external_user"),
        "threads",
        ["app_id", "external_user_id"],
        unique=False,
    )
    op.drop_column("threads", "customer_id")
    op.drop_column("apps", "config_json")
    op.drop_column("apps", "webhook_secret")
    op.drop_column("apps", "webhook_url")
    # ### end Alembic commands ###
